### ISSUE TITLE
[NAT] two NAT pools with different pool_name but same port range could be created

### ISSUE THREAD

**Issue by SavchukRomanLv** [Azure/sonic-swss#1310]
**Steps to reproduce:**
1. Enable NAT feature.
`sudo config nat feature enable`
2. Apply configuration:
`{
    "NAT_POOL": {
        "test_pool": {
            "nat_ip": "10.0.0.56",
            "nat_port": "5000-6000"
        }
    },

    "ACL_TABLE": {
        "test_acl_table": {
            "stage": "INGRESS",
            "type": "L3",
            "policy_desc": "test_policy",
            "ports": ["Ethernet8"]
        }
    },

    "ACL_RULE": {
        "test_acl_table|1": {
            "PRIORITY": "10",
            "SRC_IP": "192.168.0.0/24",
            "PACKET_ACTION": "forward"
        }
    },

    "NAT_BINDINGS": {
        "test_binding": {
            "access_list": "test_acl_table",
            "nat_pool": "test_pool"
        }
    }
}`
3. Apply config file:
`sonic-cfggen -j name_of_json_file --write-to-db`
4. Apply second config (change only pool name):
{
    "NAT_POOL": {
        "new_pool_name": {
            "nat_ip": "10.0.0.56",
            "nat_port": "5000-6000"
        }
    },

    "ACL_TABLE": {
        "test_acl_table": {
            "stage": "INGRESS",
            "type": "L3",
            "policy_desc": "test_policy",
            "ports": ["Ethernet8"]
        }
    },

    "ACL_RULE": {
        "test_acl_table|1": {
            "PRIORITY": "10",
            "SRC_IP": "192.168.0.0/24",
            "PACKET_ACTION": "forward"
        }
    },

    "NAT_BINDINGS": {
        "test_binding": {
            "access_list": "test_acl_table",
            "nat_pool": "new_pool_name"
        }
    }

}

**Actual result** : two pools with same port range were created (for example I can change port range using configuration in the bottom for specific pool_name, but if I try to change pool_name it will create new pool)

**Expected result:** when change pool name in config and than apply in to SONiC existing entry have to be updated, not new one created 

Execute `show nat config`
**Output:**
Global Values
Admin Mode     : enabled
Global Timeout : 300 secs
TCP Timeout    : 300 secs
UDP Timeout    : 120 secs

Pool Name      Global IP Range    Global Port Range
**new_pool_name  10.0.0.56          5000-6000
test_pool      10.0.0.56          5000-6000**

**Environment:**
SONiC Software Version: SONiC.HEAD.18-dirty-20200413.124039
Build commit: d09fba37
Build date: Mon Apr 13 12:48:37 UTC 2020

Platform: x86_64-arista_7170_64c
HwSKU: Arista-7170-64C
ASIC: barefoot

**Comment by AkhileshSamineni** [comment]
@SavchukRomanLv  This is expected behavior only. 

From "show nat config" output
---------------------------------------------------
Pool Name Global IP Range Global Port Range
new_pool_name 10.0.0.56 5000-6000
test_pool 10.0.0.56 5000-6000
----------------------------------------------------
The "new_pool_name" and "test_pool" are the keys for the NAT_POOL table, so user can create different nat pools with same IP and Port range or different IP and Port range. 

For example, let's take a ACL Table, where the table name is similar as pool name in Pool table

1. Create ACL Table config file
{
"ACL_TABLE": {
"test_acl_table": {
"stage": "INGRESS",
"type": "L3",
"policy_desc": "test_policy",
"ports": ["Ethernet8"]
}

2. Apply config file:
sonic-cfggen -j name_of_json_file --write-to-db

3. Create second config (change only ACL table name)
{
"ACL_TABLE": {
"test_acl_table_new": {
"stage": "INGRESS",
"type": "L3",
"policy_desc": "test_policy",
"ports": ["Ethernet8"]
}

4 Apply second config file:
sonic-cfggen -j name_of_json_file --write-to-db

root@sonic:/home/admin# show acl table
Name                      Type    Binding     Description    Stage
---------------------  ------  ----------   -------------  -------
test_acl_table_new   L3      Ethernet8    test_policy    ingress
test_acl_table           L3      Ethernet16  test_policy    ingress
root@sonic:/home/admin#

**Comment by SavchukRomanLv** [comment]
@kperumalbfn could you please reply on this? For looks weird if we can't edit pool name, otherwise we need to remove pool and configure new one. Thanks in advance.

**Comment by kperumalbfn** [comment]
@SavchukRomanLv This kind of restriction exists in other features as well(like ACL) where ACL table name would be the key. Please close this issue.

**Comment by arlakshm** [comment]
closing this issue based on comments
