### ISSUE TITLE
CRM incorrect processing for CRM_MPLS_NEXTHOP

### ISSUE THREAD

**Issue by msosyak** [Azure/sonic-swss#2044]
In `void CrmOrch::getResAvailableCounters()` for `case CrmResourceType::CRM_MPLS_NEXTHOP:` we do 
static_cast<sai_object_type_t>(crmResSaiAvailAttrMap.at(res.first)); but after this PR https://github.com/Azure/sonic-swss/pull/2008/ the value was changed from `SAI_OBJECT_TYPE_NEXT_HOP ` to `SAI_SWITCH_ATTR_AVAILABLE_IPV4_NEXTHOP_ENTRY ` so the logic in `void CrmOrch::getResAvailableCounters()` for `case CrmResourceType::CRM_MPLS_NEXTHOP:` become broken and start produce the followin errors in SONiC:
```
Nov 23 16:23:54.673681 sonic ERR swss#orchagent: :- objectTypeGetAvailability: attr SAI_L2MC_ENTRY_ATTR_PACKET_ACTION is not resource type
Nov 23 16:23:54.673681 sonic ERR swss#orchagent: :- getResAvailableCounters: Failed to get availability for object_type 53 , rv:-5
```
Link to related source code  https://github.com/Azure/sonic-swss/blob/01c243a1cfa397065f9d8f5519168bc556cf6328/orchagent/crmorch.cpp#L589
https://github.com/Azure/sonic-swss/blob/01c243a1cfa397065f9d8f5519168bc556cf6328/orchagent/crmorch.cpp#L67

**Comment by msosyak** [comment]
@smaheshm @qbdwlr @prsunny @kcudnik  Please take a look

@kperumalbfn FYI

**Comment by qbdwlr** [comment]
@smahesh @prsunny @kcudnik @kperumalbfn The fix in https://github.com/Azure/sonic-swss/pull/2008 is completely wrong and likely still triggers the same error that it was supposed to fix.
Look at the code for CrmOrch::getResAvailableCounters():  CRM_MPLS_NEXTHOP uses the SAI API sai_object_type_get_availability(); it does not call sai_switch_api->get_switch_attribute().
There are no SAI_SWITCH_ATTRs for MPLS Nexthops, because during the SAI Community review, I was asked to remove the SAI_SWITCH_ATTRs that I had defined and use sai_object_type_get_availability with SAI_OBJECT_TYPE instead.  
Not sure what platform was being tested when the issue for https://github.com/Azure/sonic-swss/pull/2008 was seen, but the correct solution is to revert the change in https://github.com/Azure/sonic-swss/pull/2008 and add support for the SAI_OBJECT_TYPE in sai_object_type_get_availability().  For VS platform, see the support I provided in VirtualSwitchSaiInterface::objectTypeGetAvailability().
Reviewing other recent changes in CrmOrch::getResAvailableCounters(), it appears that CRM_SRV6_NEXTHOP will have similar issues as CRM_MPLS_NEXTHOP and should be addressed as I have recommended.
CRM_SRV6_MY_SID_ENTRY has no unique processing and should be grouped with CRM_MPLS_INSEG and CRM_NEXTHOP_GROUP_MAP; it does not require a separate case.
I see no support for either CRM_SRV6_MY_SID_ENTRY or CRM_SRV6_NEXTHOP in vslib.  Support needs to be added in CrmOrch::getResAvailableCounters().

**Comment by prsunny** [comment]
@smaheshm , would you take a look. Looks like we may have to revert #2008

**Comment by smaheshm** [comment]
#2057
