### ISSUE TITLE
Incorrect name of table in AppDB as _VLAN_MATCH_TABLE(instead of VLAN_MATCH_TABLE) and two extra tables VLAN_MATCH_TABLE_KEY_SET and VLAN_MATCH_TABLE_DEL_SET.

### ISSUE THREAD

**Issue by ushax** [Azure/sonic-swss#2325]
I have created a new table VLAN_MATCH along the lines of VLAN_MEMBER in ConfigDB and then used vlanmgr to sync it to a new table VLAN_MATCH_TABLE(along the lines of VLAN_MEMBER_TABLE) in AppDB.  I am getting incorrect name of table in AppDB as _VLAN_MATCH_TABLE(instead of VLAN_MATCH_TABLE) and extra tables VLAN_MATCH_TABLE_KEY_SET and VLAN_MATCH_TABLE_DEL_SET on SET and DEL operations. I made a new function doVlanMatchTask(consumer) in vlanmgr and added relevent code to schema.h and vlanmgr.h:

```
void VlanMgr::doVlanMatchTask(Consumer &consumer){
 //other steps
  if (op == SET_COMMAND)
          {
              
              key = port_alias;
              key += DEFAULT_KEY_SEPARATOR;
              key += vlan_alias;
              m_appVlanMatchTableProducer.set(key, kfvFieldsValues(t));
  
          } 
//other steps
}
``` 
Am I missing any other code addition to get the proper result ?

**Comment by prsunny** [comment]
This is as per design. The table is set without "_" once you have a subscriber for it.

**Comment by nverma25** [comment]
Hello Prince, 
Actually I wrote a dummy subscriber inside portsorch.cpp for new table VLAN_MATCH in Appl_db. But after running docker orchagent again I found that still in Appl_db, _VLAN_MATCH_TABLE is getting generated and VLAN_MATCH_TABLE_KEY_SET is gone now. So what I am missing now?
Considering this situation I have few question if you can reply it will be really helpful,
Q1). Is it right that we can have certain table in config_db and same in App_db but we don't want to send any info about it to SAI?
Q2). If we have a design where we want to iterate through one table of config_db and want to update/write into two different tables in Appl_db at the same time, is it right way to do so?
Q3). when we say for any table in Appl_db , we need to have a subscriber then does SONiC design says that after subscribing the table content has to be iterated by orchagent and send down to SAI?

**Comment by prsunny** [comment]
> Hello Prince, Actually I wrote a dummy subscriber inside portsorch.cpp for new table VLAN_MATCH in Appl_db. But after running docker orchagent again I found that still in Appl_db, _VLAN_MATCH_TABLE is getting generated and VLAN_MATCH_TABLE_KEY_SET is gone now. So what I am missing now? Considering this situation I have few question if you can reply it will be really helpful, Q1). Is it right that we can have certain table in config_db and same in App_db but we don't want to send any info about it to SAI? Q2). If we have a design where we want to iterate through one table of config_db and want to update/write into two different tables in Appl_db at the same time, is it right way to do so? Q3). when we say for any table in Appl_db , we need to have a subscriber then does SONiC design says that after subscribing the table content has to be iterated by orchagent and send down to SAI?

Can you confirm by logs that the dummy subscriber is notified of the object?

1. Yes, it is possible. Some APP_DB objects are not subscribed by orchagent
2. Yes, by design. However you want to take care of ordering etc. Implementation cannot assume that tables would be notified in some specific order especially when APP_DB objects are persisted during warmreboots
3. You can use producertable instead of producerstatetable if you don't want to have orchagent subscribed for it.

**Comment by nverma25** [comment]
Thanks Prince for the Info, really helpful.
Actually, When I tried to use producer table in vlanmgr instead of producer state table as I did not want to Orchagent to subscribe and produce any data to ASIC_DB , then my table is getting produced in Appl_DB like VLAN_MATCH_TABLE_KEY_VALUE_OP_QUEUE, so what is meant by this exactly? I am not sure if I am missing some other point here in my changes.

Also is it always necessary that if we have any table or datastore in config_db then same has to be present in Appl_db to maintain consistency across databases ?
