### ISSUE TITLE
orchagent cannot rebuild xxxorch.cpp when port.h changed which is included by xxxorch.h

### ISSUE THREAD

**Issue by sunnogo** [Azure/sonic-swss#568]
To avoid re-compile all code every time, I modified slave.mk:

```
DEB_BUILD_OPTIONS=$($*_DEB_BUILD_OPTIONS) dpkg-buildpackage -rfakeroot -b -us -uc -nc -j$(SONIC_CONFIG_MAKE_JOBS) --as-root -T$($*_DPKG_TARGET) $(LOG),
DEB_BUILD_OPTIONS=$($*_DEB_BUILD_OPTIONS) dpkg-buildpackage -rfakeroot -b -us -uc -nc -j$(SONIC_CONFIG_MAKE_JOBS) $(LOG)
```

It's time consuming if we don't add `-nc` no-pre-clean option in dpkg-buildpackage.

But I found that Makefile in orchagent doesn't re-compile cpp source when the headers it includes doesn't change but header in header changed.

**Comment by lguohan** [comment]
usually, the cleanest way to build is do pre-clean.

what is the case for header in header changed? What headers do we depends in the headers of swss?

**Comment by jeromesunt** [comment]
Hi @lguohan , yes, I know it's the best and cleanest way to do pre-clean in the beginning of building. But it's not friendly to developer, it recompiles all the source codes and is really time-consuming.

So this issue is for developer only, not for all users. I add `-nc` option to avoid clean `.o` that means we don't have to recompile all the source codes when we modify one.

We may change interface MAC address, so we add a `m_mac` to Class Port (port.h). portsorch.h include port.h, and portsorch.cpp includes portsorch.h. However, when port.h changed, portsorch.cpp hasn't been re-compiled automatically.

**Comment by jipanyang** [comment]
Does the problem have any chance of being related to the missing backslash in this Makefile.am
https://github.com/Azure/sonic-swss/blob/dcf6c905410f08b004e880dbed56823d29e7bd5e/orchagent/Makefile.am#L69 ?

**Comment by sunnogo** [comment]
@jipanyang nope. I think it's another issue.

**Comment by sunnogo** [comment]
Yes, I do the same thing like you when change a header file. There're some ways to fix this header dependency issue ([stackoverflow](https://stackoverflow.com/questions/2394609/makefile-header-dependencies)), but I don't want to fix it now. We need to develop more features first.

Let's close this issue first as it's just a developer issue.
